# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/christopher/xwiimote-mouse-driver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/christopher/xwiimote-mouse-driver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/christopher/xwiimote-mouse-driver/CMakeFiles /home/christopher/xwiimote-mouse-driver//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/christopher/xwiimote-mouse-driver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mouse-test

# Build rule for target.
mouse-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mouse-test
.PHONY : mouse-test

# fast build rule for target.
mouse-test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mouse-test.dir/build.make CMakeFiles/mouse-test.dir/build
.PHONY : mouse-test/fast

#=============================================================================
# Target rules for targets named xwiimote-test

# Build rule for target.
xwiimote-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xwiimote-test
.PHONY : xwiimote-test

# fast build rule for target.
xwiimote-test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xwiimote-test.dir/build.make CMakeFiles/xwiimote-test.dir/build
.PHONY : xwiimote-test/fast

#=============================================================================
# Target rules for targets named test-maths

# Build rule for target.
test-maths: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-maths
.PHONY : test-maths

# fast build rule for target.
test-maths/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-maths.dir/build.make CMakeFiles/test-maths.dir/build
.PHONY : test-maths/fast

#=============================================================================
# Target rules for targets named sockpp

# Build rule for target.
sockpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sockpp
.PHONY : sockpp

# fast build rule for target.
sockpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sockpp.dir/build.make CMakeFiles/sockpp.dir/build
.PHONY : sockpp/fast

#=============================================================================
# Target rules for targets named sockpp-install

# Build rule for target.
sockpp-install: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sockpp-install
.PHONY : sockpp-install

# fast build rule for target.
sockpp-install/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sockpp-install.dir/build.make CMakeFiles/sockpp-install.dir/build
.PHONY : sockpp-install/fast

#=============================================================================
# Target rules for targets named waywiimote-mouse-driver

# Build rule for target.
waywiimote-mouse-driver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 waywiimote-mouse-driver
.PHONY : waywiimote-mouse-driver

# fast build rule for target.
waywiimote-mouse-driver/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/build
.PHONY : waywiimote-mouse-driver/fast

src/driver/controlsocket.o: src/driver/controlsocket.cpp.o
.PHONY : src/driver/controlsocket.o

# target to build an object file
src/driver/controlsocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/controlsocket.cpp.o
.PHONY : src/driver/controlsocket.cpp.o

src/driver/controlsocket.i: src/driver/controlsocket.cpp.i
.PHONY : src/driver/controlsocket.i

# target to preprocess a source file
src/driver/controlsocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/controlsocket.cpp.i
.PHONY : src/driver/controlsocket.cpp.i

src/driver/controlsocket.s: src/driver/controlsocket.cpp.s
.PHONY : src/driver/controlsocket.s

# target to generate assembly for a file
src/driver/controlsocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/controlsocket.cpp.s
.PHONY : src/driver/controlsocket.cpp.s

src/driver/device.o: src/driver/device.cpp.o
.PHONY : src/driver/device.o

# target to build an object file
src/driver/device.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/device.cpp.o
.PHONY : src/driver/device.cpp.o

src/driver/device.i: src/driver/device.cpp.i
.PHONY : src/driver/device.i

# target to preprocess a source file
src/driver/device.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/device.cpp.i
.PHONY : src/driver/device.cpp.i

src/driver/device.s: src/driver/device.cpp.s
.PHONY : src/driver/device.s

# target to generate assembly for a file
src/driver/device.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/device.cpp.s
.PHONY : src/driver/device.cpp.s

src/driver/driverextra.o: src/driver/driverextra.cpp.o
.PHONY : src/driver/driverextra.o

# target to build an object file
src/driver/driverextra.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/driverextra.cpp.o
.PHONY : src/driver/driverextra.cpp.o

src/driver/driverextra.i: src/driver/driverextra.cpp.i
.PHONY : src/driver/driverextra.i

# target to preprocess a source file
src/driver/driverextra.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/driverextra.cpp.i
.PHONY : src/driver/driverextra.cpp.i

src/driver/driverextra.s: src/driver/driverextra.cpp.s
.PHONY : src/driver/driverextra.s

# target to generate assembly for a file
src/driver/driverextra.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/driverextra.cpp.s
.PHONY : src/driver/driverextra.cpp.s

src/driver/drivermain.o: src/driver/drivermain.cpp.o
.PHONY : src/driver/drivermain.o

# target to build an object file
src/driver/drivermain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/drivermain.cpp.o
.PHONY : src/driver/drivermain.cpp.o

src/driver/drivermain.i: src/driver/drivermain.cpp.i
.PHONY : src/driver/drivermain.i

# target to preprocess a source file
src/driver/drivermain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/drivermain.cpp.i
.PHONY : src/driver/drivermain.cpp.i

src/driver/drivermain.s: src/driver/drivermain.cpp.s
.PHONY : src/driver/drivermain.s

# target to generate assembly for a file
src/driver/drivermain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/drivermain.cpp.s
.PHONY : src/driver/drivermain.cpp.s

src/driver/filterlayers/clustering.o: src/driver/filterlayers/clustering.cpp.o
.PHONY : src/driver/filterlayers/clustering.o

# target to build an object file
src/driver/filterlayers/clustering.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/filterlayers/clustering.cpp.o
.PHONY : src/driver/filterlayers/clustering.cpp.o

src/driver/filterlayers/clustering.i: src/driver/filterlayers/clustering.cpp.i
.PHONY : src/driver/filterlayers/clustering.i

# target to preprocess a source file
src/driver/filterlayers/clustering.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/filterlayers/clustering.cpp.i
.PHONY : src/driver/filterlayers/clustering.cpp.i

src/driver/filterlayers/clustering.s: src/driver/filterlayers/clustering.cpp.s
.PHONY : src/driver/filterlayers/clustering.s

# target to generate assembly for a file
src/driver/filterlayers/clustering.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/filterlayers/clustering.cpp.s
.PHONY : src/driver/filterlayers/clustering.cpp.s

src/driver/filterlayers/predictive.o: src/driver/filterlayers/predictive.cpp.o
.PHONY : src/driver/filterlayers/predictive.o

# target to build an object file
src/driver/filterlayers/predictive.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/filterlayers/predictive.cpp.o
.PHONY : src/driver/filterlayers/predictive.cpp.o

src/driver/filterlayers/predictive.i: src/driver/filterlayers/predictive.cpp.i
.PHONY : src/driver/filterlayers/predictive.i

# target to preprocess a source file
src/driver/filterlayers/predictive.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/filterlayers/predictive.cpp.i
.PHONY : src/driver/filterlayers/predictive.cpp.i

src/driver/filterlayers/predictive.s: src/driver/filterlayers/predictive.cpp.s
.PHONY : src/driver/filterlayers/predictive.s

# target to generate assembly for a file
src/driver/filterlayers/predictive.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/filterlayers/predictive.cpp.s
.PHONY : src/driver/filterlayers/predictive.cpp.s

src/driver/filterlayers/smoother.o: src/driver/filterlayers/smoother.cpp.o
.PHONY : src/driver/filterlayers/smoother.o

# target to build an object file
src/driver/filterlayers/smoother.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/filterlayers/smoother.cpp.o
.PHONY : src/driver/filterlayers/smoother.cpp.o

src/driver/filterlayers/smoother.i: src/driver/filterlayers/smoother.cpp.i
.PHONY : src/driver/filterlayers/smoother.i

# target to preprocess a source file
src/driver/filterlayers/smoother.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/filterlayers/smoother.cpp.i
.PHONY : src/driver/filterlayers/smoother.cpp.i

src/driver/filterlayers/smoother.s: src/driver/filterlayers/smoother.cpp.s
.PHONY : src/driver/filterlayers/smoother.s

# target to generate assembly for a file
src/driver/filterlayers/smoother.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/filterlayers/smoother.cpp.s
.PHONY : src/driver/filterlayers/smoother.cpp.s

src/driver/filterlayers/towedcircle.o: src/driver/filterlayers/towedcircle.cpp.o
.PHONY : src/driver/filterlayers/towedcircle.o

# target to build an object file
src/driver/filterlayers/towedcircle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/filterlayers/towedcircle.cpp.o
.PHONY : src/driver/filterlayers/towedcircle.cpp.o

src/driver/filterlayers/towedcircle.i: src/driver/filterlayers/towedcircle.cpp.i
.PHONY : src/driver/filterlayers/towedcircle.i

# target to preprocess a source file
src/driver/filterlayers/towedcircle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/filterlayers/towedcircle.cpp.i
.PHONY : src/driver/filterlayers/towedcircle.cpp.i

src/driver/filterlayers/towedcircle.s: src/driver/filterlayers/towedcircle.cpp.s
.PHONY : src/driver/filterlayers/towedcircle.s

# target to generate assembly for a file
src/driver/filterlayers/towedcircle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/filterlayers/towedcircle.cpp.s
.PHONY : src/driver/filterlayers/towedcircle.cpp.s

src/driver/settings.o: src/driver/settings.cpp.o
.PHONY : src/driver/settings.o

# target to build an object file
src/driver/settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/settings.cpp.o
.PHONY : src/driver/settings.cpp.o

src/driver/settings.i: src/driver/settings.cpp.i
.PHONY : src/driver/settings.i

# target to preprocess a source file
src/driver/settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/settings.cpp.i
.PHONY : src/driver/settings.cpp.i

src/driver/settings.s: src/driver/settings.cpp.s
.PHONY : src/driver/settings.s

# target to generate assembly for a file
src/driver/settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/settings.cpp.s
.PHONY : src/driver/settings.cpp.s

src/driver/stringtools.o: src/driver/stringtools.cpp.o
.PHONY : src/driver/stringtools.o

# target to build an object file
src/driver/stringtools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/stringtools.cpp.o
.PHONY : src/driver/stringtools.cpp.o

src/driver/stringtools.i: src/driver/stringtools.cpp.i
.PHONY : src/driver/stringtools.i

# target to preprocess a source file
src/driver/stringtools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/stringtools.cpp.i
.PHONY : src/driver/stringtools.cpp.i

src/driver/stringtools.s: src/driver/stringtools.cpp.s
.PHONY : src/driver/stringtools.s

# target to generate assembly for a file
src/driver/stringtools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/stringtools.cpp.s
.PHONY : src/driver/stringtools.cpp.s

src/driver/virtualmouse.o: src/driver/virtualmouse.cpp.o
.PHONY : src/driver/virtualmouse.o

# target to build an object file
src/driver/virtualmouse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mouse-test.dir/build.make CMakeFiles/mouse-test.dir/src/driver/virtualmouse.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/virtualmouse.cpp.o
.PHONY : src/driver/virtualmouse.cpp.o

src/driver/virtualmouse.i: src/driver/virtualmouse.cpp.i
.PHONY : src/driver/virtualmouse.i

# target to preprocess a source file
src/driver/virtualmouse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mouse-test.dir/build.make CMakeFiles/mouse-test.dir/src/driver/virtualmouse.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/virtualmouse.cpp.i
.PHONY : src/driver/virtualmouse.cpp.i

src/driver/virtualmouse.s: src/driver/virtualmouse.cpp.s
.PHONY : src/driver/virtualmouse.s

# target to generate assembly for a file
src/driver/virtualmouse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mouse-test.dir/build.make CMakeFiles/mouse-test.dir/src/driver/virtualmouse.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/virtualmouse.cpp.s
.PHONY : src/driver/virtualmouse.cpp.s

src/driver/xdg-output-protocol.o: src/driver/xdg-output-protocol.c.o
.PHONY : src/driver/xdg-output-protocol.o

# target to build an object file
src/driver/xdg-output-protocol.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/xdg-output-protocol.c.o
.PHONY : src/driver/xdg-output-protocol.c.o

src/driver/xdg-output-protocol.i: src/driver/xdg-output-protocol.c.i
.PHONY : src/driver/xdg-output-protocol.i

# target to preprocess a source file
src/driver/xdg-output-protocol.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/xdg-output-protocol.c.i
.PHONY : src/driver/xdg-output-protocol.c.i

src/driver/xdg-output-protocol.s: src/driver/xdg-output-protocol.c.s
.PHONY : src/driver/xdg-output-protocol.s

# target to generate assembly for a file
src/driver/xdg-output-protocol.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/waywiimote-mouse-driver.dir/build.make CMakeFiles/waywiimote-mouse-driver.dir/src/driver/xdg-output-protocol.c.s
.PHONY : src/driver/xdg-output-protocol.c.s

src/testapps/mouse-test.o: src/testapps/mouse-test.cpp.o
.PHONY : src/testapps/mouse-test.o

# target to build an object file
src/testapps/mouse-test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mouse-test.dir/build.make CMakeFiles/mouse-test.dir/src/testapps/mouse-test.cpp.o
.PHONY : src/testapps/mouse-test.cpp.o

src/testapps/mouse-test.i: src/testapps/mouse-test.cpp.i
.PHONY : src/testapps/mouse-test.i

# target to preprocess a source file
src/testapps/mouse-test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mouse-test.dir/build.make CMakeFiles/mouse-test.dir/src/testapps/mouse-test.cpp.i
.PHONY : src/testapps/mouse-test.cpp.i

src/testapps/mouse-test.s: src/testapps/mouse-test.cpp.s
.PHONY : src/testapps/mouse-test.s

# target to generate assembly for a file
src/testapps/mouse-test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mouse-test.dir/build.make CMakeFiles/mouse-test.dir/src/testapps/mouse-test.cpp.s
.PHONY : src/testapps/mouse-test.cpp.s

src/testapps/testmaths.o: src/testapps/testmaths.cpp.o
.PHONY : src/testapps/testmaths.o

# target to build an object file
src/testapps/testmaths.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-maths.dir/build.make CMakeFiles/test-maths.dir/src/testapps/testmaths.cpp.o
.PHONY : src/testapps/testmaths.cpp.o

src/testapps/testmaths.i: src/testapps/testmaths.cpp.i
.PHONY : src/testapps/testmaths.i

# target to preprocess a source file
src/testapps/testmaths.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-maths.dir/build.make CMakeFiles/test-maths.dir/src/testapps/testmaths.cpp.i
.PHONY : src/testapps/testmaths.cpp.i

src/testapps/testmaths.s: src/testapps/testmaths.cpp.s
.PHONY : src/testapps/testmaths.s

# target to generate assembly for a file
src/testapps/testmaths.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-maths.dir/build.make CMakeFiles/test-maths.dir/src/testapps/testmaths.cpp.s
.PHONY : src/testapps/testmaths.cpp.s

src/testapps/xwiimote-test.o: src/testapps/xwiimote-test.cpp.o
.PHONY : src/testapps/xwiimote-test.o

# target to build an object file
src/testapps/xwiimote-test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xwiimote-test.dir/build.make CMakeFiles/xwiimote-test.dir/src/testapps/xwiimote-test.cpp.o
.PHONY : src/testapps/xwiimote-test.cpp.o

src/testapps/xwiimote-test.i: src/testapps/xwiimote-test.cpp.i
.PHONY : src/testapps/xwiimote-test.i

# target to preprocess a source file
src/testapps/xwiimote-test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xwiimote-test.dir/build.make CMakeFiles/xwiimote-test.dir/src/testapps/xwiimote-test.cpp.i
.PHONY : src/testapps/xwiimote-test.cpp.i

src/testapps/xwiimote-test.s: src/testapps/xwiimote-test.cpp.s
.PHONY : src/testapps/xwiimote-test.s

# target to generate assembly for a file
src/testapps/xwiimote-test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xwiimote-test.dir/build.make CMakeFiles/xwiimote-test.dir/src/testapps/xwiimote-test.cpp.s
.PHONY : src/testapps/xwiimote-test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sockpp"
	@echo "... sockpp-install"
	@echo "... mouse-test"
	@echo "... test-maths"
	@echo "... waywiimote-mouse-driver"
	@echo "... xwiimote-test"
	@echo "... src/driver/controlsocket.o"
	@echo "... src/driver/controlsocket.i"
	@echo "... src/driver/controlsocket.s"
	@echo "... src/driver/device.o"
	@echo "... src/driver/device.i"
	@echo "... src/driver/device.s"
	@echo "... src/driver/driverextra.o"
	@echo "... src/driver/driverextra.i"
	@echo "... src/driver/driverextra.s"
	@echo "... src/driver/drivermain.o"
	@echo "... src/driver/drivermain.i"
	@echo "... src/driver/drivermain.s"
	@echo "... src/driver/filterlayers/clustering.o"
	@echo "... src/driver/filterlayers/clustering.i"
	@echo "... src/driver/filterlayers/clustering.s"
	@echo "... src/driver/filterlayers/predictive.o"
	@echo "... src/driver/filterlayers/predictive.i"
	@echo "... src/driver/filterlayers/predictive.s"
	@echo "... src/driver/filterlayers/smoother.o"
	@echo "... src/driver/filterlayers/smoother.i"
	@echo "... src/driver/filterlayers/smoother.s"
	@echo "... src/driver/filterlayers/towedcircle.o"
	@echo "... src/driver/filterlayers/towedcircle.i"
	@echo "... src/driver/filterlayers/towedcircle.s"
	@echo "... src/driver/settings.o"
	@echo "... src/driver/settings.i"
	@echo "... src/driver/settings.s"
	@echo "... src/driver/stringtools.o"
	@echo "... src/driver/stringtools.i"
	@echo "... src/driver/stringtools.s"
	@echo "... src/driver/virtualmouse.o"
	@echo "... src/driver/virtualmouse.i"
	@echo "... src/driver/virtualmouse.s"
	@echo "... src/driver/xdg-output-protocol.o"
	@echo "... src/driver/xdg-output-protocol.i"
	@echo "... src/driver/xdg-output-protocol.s"
	@echo "... src/testapps/mouse-test.o"
	@echo "... src/testapps/mouse-test.i"
	@echo "... src/testapps/mouse-test.s"
	@echo "... src/testapps/testmaths.o"
	@echo "... src/testapps/testmaths.i"
	@echo "... src/testapps/testmaths.s"
	@echo "... src/testapps/xwiimote-test.o"
	@echo "... src/testapps/xwiimote-test.i"
	@echo "... src/testapps/xwiimote-test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

